Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
plt.figure(figsize=(8, 6))
sns.scatterplot(x=X_cleaned['Bilirubin'], y=X_cleaned['Albumin'], hue=y_cleaned)
plt.title("Scatter Plot - Bilirubin vs Albumin")
plt.xlabel("Bilirubin")
plt.ylabel("Albumin")
plt.grid(True)
plt.show()

------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 2[0m
[1;32m      1[0m plt[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m8[39m, [38;5;241m6[39m))
[0;32m----> 2[0m sns[38;5;241m.[39mscatterplot(x[38;5;241m=[39m[43mX_cleaned[49m[[38;5;124m'[39m[38;5;124mBilirubin[39m[38;5;124m'[39m], y[38;5;241m=[39mX_cleaned[[38;5;124m'[39m[38;5;124mAlbumin[39m[38;5;124m'[39m], hue[38;5;241m=[39my_cleaned)
[1;32m      3[0m plt[38;5;241m.[39mtitle([38;5;124m"[39m[38;5;124mScatter Plot - Bilirubin vs Albumin[39m[38;5;124m"[39m)
[1;32m      4[0m plt[38;5;241m.[39mxlabel([38;5;124m"[39m[38;5;124mBilirubin[39m[38;5;124m"[39m)

[0;31mNameError[0m: name 'X_cleaned' is not defined

